### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by pranjan77** [soedinglab/PEnG-motif#26]
I am having hard time installing on a machine
Linux 64dc5edce39d 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

It would be good if you have Dockerfile for installing these in a standard ubuntu or other linux machine.

**Comment by croth1** [comment]
@pranjan77, thanks for the suggestion. A docker image is certainly a good idea. I will ping you, once I have finished it!

**Comment by croth1** [comment]
@pranjan77, sorry for the delay. I have uploaded a docker-file that can run BaMMmotif and PEnG-motif and our utility scripts.

Please find the details in the README. 

https://github.com/soedinglab/PEnG-motif/blob/master/README.md#docker-image

If you have any questions, please don't hesitate to ask!

**Comment by pranjan77** [comment]
@croth1 Thank you very much! The command as provided didnt work for me. Something like the following gave me the output I was expecting.
docker run -v $PWD:/mnt soedinglab/bamm-suite peng_motif /mnt/test.fasta

Can you also provided link to the Dockerfile?

**Comment by croth1** [comment]
> The command as provided didnt work for me.

That's odd. Can you post the command you tried so I can troubleshoot?

> Can you also provided link to the Dockerfile?

It's currently in a private repo, I pasted it for you.

```
FROM alpine
MAINTAINER Christian Roth <christian.roth@mpibpc.mpg.de>

ENV PENG_VERSION=1.0.0

RUN apk add --update wget g++ cmake boost-dev make
RUN wget https://github.com/soedinglab/PEnG-motif/archive/${PENG_VERSION}.tar.gz
RUN tar xzf ${PENG_VERSION}.tar.gz
RUN mkdir build
WORKDIR build
RUN cmake ../PEnG-motif-${PENG_VERSION} -DCMAKE_INSTALL_PREFIX=/bamm
RUN make -j4 install

RUN wget https://github.com/soedinglab/BaMMmotif2/archive/v2.0.tar.gz
RUN tar xzf v2.0.tar.gz
RUN mkdir build_bamm
WORKDIR build_bamm
RUN cmake ../BaMMmotif2-2.0 -DCMAKE_INSTALL_PREFIX=/bamm
RUN make -j4 install


FROM alpine
RUN apk add --update python3-dev python3 boost R-dev R gcc libgcc libc-dev
RUN R -e 'install.packages(c("argparse", "zoo", "fdrtool", "LSD"), repos="http://cran.us.r-project.org")'
RUN python3 -m pip install numpy

COPY --from=0 /bamm /bamm
RUN ln -s /usr/bin/python3 /bamm/bin/python
RUN chmod -R +rx /bamm/bin
ENV PATH "$PATH:/bamm/bin"
WORKDIR /data
```
