### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by AnosAhmad** [soedinglab/PEnG-motif#34]
Hello Developer, 

My name is Enas and I am a Ph.D. student. My research focuses on static code analysis. I was looking for open-source software to collect some static code analysis tool warnings. I checked your source code, and I ran one of static code analysis tools over the source code. A number of warnings were generated; some of them may represent true defects in the source code and some may represent false reports, where the tool shows a defect but in reality there is none. 

I need your help by going through the warnings and checking if any of them represent a true defect in your source code. To do that, kindly find the attached file, which contains the warnings. 

Your response and help are highly appreciated. 

Thanks, 
Enas 
 
[FF.xlsx](https://github.com/soedinglab/PEnG-motif/files/2873399/FF.xlsx)

**Comment by croth1** [comment]
Dear Enas,

We appreciate your interest in improving our software, but I feel that the github issue tracker may not be well suited for this kind of discussion.

Please contact us directly at bamm@mpibpc.mpg.de. 

In your email please include:
 - The suggested problems in text format (e.g. tab separated/csv file)
 - As much annotation and background as possible to make it easier for us to understand the suggested flaws.

Best,
Christian
